{% set name = "pzflow" %}
{% set version = "3.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jfcrenshaw/pzflow/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8a8fb68155700f1463b86314b0a63c7255fdb0ec63181e23206a663e178811ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - poetry-core >=1.0.0
  run:
    # I don't think any of these constraints are real but here I am
    - python >=3.8
    - jax >=0.4.2,<0.5
    - optax >=0.1.4,<0.2
    - pandas >=1.1
    - dill >=0.3.6,<0.4
    - tqdm >=4.64.1,<5

test:
  imports:
    - pzflow
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jfcrenshaw/pzflow
  summary: Probabilistic modeling of tabular data with normalizing flows.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
