{% set name = "pzflow" %}
{% set version = "3.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jfcrenshaw/pzflow/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 341bb1a1d3127a895ace8e147710b5eeb1e19b17ece75c3e2c0b729a05aaf7f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    # I don't think any of these constraints are real but here I am
    - python >={{ python_min }}
    - jax >=0.5.3,<0.6.0
    - optax >=0.2.4,<0.3
    - pandas >=1.1
    - dill >=0.3.6,<0.4
    - tqdm >=4.64.1,<5

test:
  imports:
    - pzflow
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/jfcrenshaw/pzflow
  summary: Probabilistic modeling of tabular data with normalizing flows.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
